AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template
Resources:
  BucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: STD21029
  SSMParameters:
    Type: AWS::SSM::Parameter
    Properties:
      Name: BucketS3
      Type: String
      Value: !GetAtt BucketS3.Arn
