Resources:
  BucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: STD21029
  SSMParameters:
    Type: AWS::SSM::Parameter
    properties:
      Name: !Ref BucketS3
      Type: String
      Value: !GetAtt BucketS3.Arn
